config/routes.rb
Rails.application.routes.draw do

	resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
	validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    @dogs = Dog.page(params[:page]).per(5)
    
    if params[:id].present?
      @dog = Dog.find(params[:id])
    else
      @dog = Dog.new
    end

  end

  def new
  	@dog = Dog.new
  end

  def show
  	@dog = Dog.find(params[:id])
  end

  def edit
  	@dog = Dog.find(params[:id])

  end

  def update
  	@dog = Dog.find(params[:id])
  	@dog.update(event_params)

  	flash[:notice] = "event was successfully updated"

    redirect_to dog_url

  end

  def destroy
  	@dog = Dog.find(params[:id])
  	@dog.destroy
  	flash[:alert] = "event was successfully deleted"
  	redirect_to dogs_url
  end


  def create
  	@dog = Dog.new(event_params)
  	
    if @dog.save
  	 flash[:notice] = "event was successfully created"
    else
      render :action => :new
    end

  end



  
  private

  def event_params
  	params.require(:dog).permit(:name, :descrip, :date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/edit.html.erb
<%= form_for @dog , :url => {:controller => "dogs" , :action => "update" , :id => @dog} do |f| %>
	
	<%= f.label :name , "name"%>
	<%= f.text_field :name %>

	<%= f.label :descrip , "descrip"%>
	<%= f.text_field :descrip %>

	<%= f.submit "update" %>

<% end %>

app/views/dogs/index.html.erb
<h1> List </h1>

<% if params[:id] %>
    <%= form_for @dog do |f| %>
        
        <%= f.label :name , "name"%>
        <%= f.text_field :name %>

        <%= f.label :descrip , "descrip"%>
        <%= f.text_field :descrip %>

        <%= f.label :date %>
        <%= f.date_select :date %>

        <%= f.submit "EDIT" %>
        <%= link_to 'New form' , dogs_url , :class => "btn btn-default" %>

    <% end %>
    <% else %>
        <%= form_for @dog do |f| %>
            
            <%= f.label :name , "name" %>
            <%= f.text_field :name %>

            <%= f.label :descrip , "descrip" %>
            <%= f.text_field :descrip %>

            <%= f.label :date %>
            <%= f.date_select :date %>

            <%= f.submit "NEW" %>


    <% end %>
<% end %>




<%= paginate @dogs %>

<table class= 'table'>

<thead>
      <tr>
        <th>name</th>
        <th>description</th>
        <th>show</th>
        <th>Date</th>
        <th>edit</th>
        <th>Get J</th>
        <th>delete</th>
      </tr>
    </thead>

<% @dogs.each do |d| %>
	
    <tbody>
 	  <tr>
	 	  <td><%= d.name %></td>
	 	  <td><%= d.descrip %></td>
		  <td><%= link_to 'show' , dog_path(d) , :class => "btn btn-default" %></td>
          <td><%= d.date %></td>
		  <td><%= link_to 'edit' , dogs_path(id: d, page: params[:page]) , :class => "btn btn-default" %></td>
		  <td><%= link_to 'Get json' , dog_path(d, :format => :json) , :class => "btn btn-default"%></td>
		  <td><%= link_to 'delete', dog_path(d), :class => "btn btn-default" , :method => :delete, :data => { :confirm => "Are you sure?" } %></td>
	  </tr>
	  
<% end %>
	</tbody>
</table>


<%= link_to 'New Event', new_dog_path() %>

app/views/dogs/new.html.erb
<%= form_for @dog , :url => {:controller => "dogs" , :action => "create"} do |f| %>
	
	<%= f.label :name , "name"%>
	<%= f.text_field :name %>

	<%= f.label :descrip , "descrip"%>
	<%= f.text_field :descrip %>

    <%= f.label :date %>
	<%= f.date_select :date %>

	<%= f.submit "create" %>

<% end %>

app/views/dogs/show.html.erb
<%= @dog.name %>
<%= @dog.descrip %>

<p><%= link_to 'Back to index', :controller => 'dogs', :action => 'index' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>C3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>

    <div class = "container">
      <div class = "row">
        <div class = "col-md-12" >
            <p style="color: green"><%= flash[:notice] %></p>
            <p style="color: red"><%= flash[:alert] %></p>
            <%= yield %>
        </div>
      </div>
    </div>
  	

  </body>
</html>